const formulaForm = document.getElementById('formulaForm');
const formulaInput = document.getElementById('formulaInput');
const answerForm = document.getElementById('answerForm');
const answerInput = document.getElementById('answerInput');
const notification = document.getElementById('notification');
const character = document.getElementById('character');
const scoreElement = document.querySelector('.scoreboard.left');

// set global variables 
let score = 0;
let operand1 = 0; 
let operand2 = 0; 
let plyrNum = 1;

// generate a question that we can then solve!
formulaForm.addEventListener('submit', function(e) {
  e.preventDefault();

  // Generate a random multiplication expression
  operand1 = Math.floor(Math.random() * 10) + 1;
  operand2 = Math.floor(Math.random() * 10) + 1;
  const expression = `${operand1} × ${operand2}`;

  // Display the next expression
  formulaInput.placeholder = expression;
  formulaInput.value = '';
});

// do the valiation of the expression generated by request
answerForm.addEventListener('submit', function(e) {
    e.preventDefault();
  
    const answerGiven = answerInput.value;
  
    // Validate the answer
    if (parseInt(answerGiven) === operand1 * operand2) {
      notification.textContent = 'OOOOOHHHH YEAAAA!';
      score++;
      scoreElement.textContent = 'Player'+plyrNum+' Score: ' + score;
      moveCharacter();
    } else {
      notification.textContent = 'Wrong answer. Try again.';
    }
  
  });

function moveCharacter() {
  // Move the character here
  const containerWidth = document.getElementById('main').offsetWidth;
  const containerHeight = document.getElementById('main').offsetHeight;

  const randomLeft = Math.floor(Math.random() * (containerWidth - 50));
  const randomTop = Math.floor(Math.random() * (containerHeight - 50));

  character.style.left = randomLeft + 'px';
  character.style.top = randomTop + 'px';
}
